In [38]:
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib as plt
import pandas as pd
import os
import matplotlib.pyplot as plt
import numpy as np
from collections import defaultdict
import plotly.offline as py
py.init_notebook_mode(connected=True)
import plotly.graph_objs as go

import matplotlib.pyplot as plt
from collections import defaultdict


(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()




In [4]:
X = x_train.reshape(len(x_train),-1)
Y = y_train

#Normalize 
X = X.astype(float) / 255.

print(X.shape)
print(X[0].shape)




(60000, 784)
(784,)


In [5]:
from sklearn.cluster import MiniBatchKMeans

n_digits = len(np.unique(y_test))

kmeans = MiniBatchKMeans(n_clusters = n_digits)

kmeans.fit(X)

kmeans.labels_

10


array([0, 6, 5, ..., 4, 1, 9], dtype=int32)

In [6]:
def infer_cluster_labels(kmeans, actual_labels):


    inferred_labels = {}

    for i in range(kmeans.n_clusters):

        labels = []
        index = np.where(kmeans.labels_ == i)

        labels.append(actual_labels[index])

        if len(labels[0]) == 1:
            counts = np.bincount(labels[0])
        else:
            counts = np.bincount(np.squeeze(labels))

        if np.argmax(counts) in inferred_labels:
            inferred_labels[np.argmax(counts)].append(i)
        else:
            inferred_labels[np.argmax(counts)] = [i]

        
    return inferred_labels  

def infer_data_labels(X_labels, cluster_labels):
  
    
    predicted_labels = np.zeros(len(X_labels)).astype(np.uint8)
    
    for i, cluster in enumerate(X_labels):
        for key, value in cluster_labels.items():
            if cluster in value:
                predicted_labels[i] = key
                
    return predicted_labels

In [7]:
cluster_labels = infer_cluster_labels(kmeans, Y)
X_clusters = kmeans.predict(X)
predicted_labels = infer_data_labels(X_clusters, cluster_labels)
print(predicted_labels[:20])
print(Y[:20])

[3 0 4 1 9 2 1 3 1 7 3 1 3 6 1 7 2 1 6 1]
[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9]


In [49]:
clusters = [10]

for n_clusters in clusters:
    estimator = MiniBatchKMeans(n_clusters = n_clusters)
    estimator.fit(X)

    cluster_labels = infer_cluster_labels(estimator, Y)
    predicted_Y = infer_data_labels(estimator.labels_, cluster_labels)
    
    print('Accuracy: {}\n'.format(metrics.accuracy_score(Y, predicted_Y)))

Accuracy: 0.58175



In [41]:
X_test = x_test.reshape(len(x_test),-1)
X_test = X_test.astype(float) / 255.
Y_test = y_test

In [48]:
clusters = [10]

for n_clusters in clusters:
    estimator = MiniBatchKMeans(n_clusters = n_clusters)
    estimator.fit(X_test)

    
    cluster_labels = infer_cluster_labels(estimator, Y_test)
    predicted_Y = infer_data_labels(estimator.labels_, cluster_labels)
    
    print('Accuracy: {}\n'.format(metrics.accuracy_score(Y_test, predicted_Y)))

Accuracy: 0.5244

